//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoPatrimonio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadioBase
    {
        public RadioBase()
        {
            this.Tag = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public int Id_Setor { get; set; }
        public string Descricao { get; set; }
        public string Resumo { get; set; }
    
        public virtual Setor Setor { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
