//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoPatrimonio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int Id { get; set; }
        public int Id_RadioBase { get; set; }
        public int Id_Patrimonio { get; set; }
        public int Id_Tag_HTML { get; set; }
        public string Descricao { get; set; }
        public string Resumo { get; set; }
        public string Pos_X { get; set; }
        public string CssTop { get; set; }
        public string CssLeft { get; set; }
        public string Temperatura { get; set; }
        public string Acelerometro { get; set; }
        public string MovLeveMesRB { get; set; }
        public string CargaBateria { get; set; }
        public string EstadoRemocao { get; set; }
        public Nullable<bool> Ativa { get; set; }
        public Nullable<int> Id_Conta { get; set; }
        public Nullable<int> Id_Centro { get; set; }
    
        public virtual Patrimonio Patrimonio { get; set; }
        public virtual RadioBase RadioBase { get; set; }
        public virtual Tag_HTML Tag_HTML { get; set; }
    }
}
