//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoPatrimonio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag_HTML
    {
        public Tag_HTML()
        {
            this.Tag = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public int Id_Div { get; set; }
        public int Id_Hyperlink { get; set; }
        public int Id_Item_li { get; set; }
        public int Id_SVG_Symbol { get; set; }
        public string CssTop { get; set; }
        public string CssLeft { get; set; }
        public string Nome { get; set; }
        public string Descrição { get; set; }
    
        public virtual Tag_Div Tag_Div { get; set; }
        public virtual Tag_Hyperlink Tag_Hyperlink { get; set; }
        public virtual Tag_Item_li Tag_Item_li { get; set; }
        public virtual Tag_SVG_Symbol Tag_SVG_Symbol { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
